"""Add_Tabela_Rent

Revision ID: 081b54006769
Revises: 734440b66ab8
Create Date: 2025-05-04 17:10:24.046310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081b54006769'
down_revision = '734440b66ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('rent_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rents')
    # ### end Alembic commands ###
