"""Add_Avaliacao_Tabela_Movie

Revision ID: beb9c950e5d3
Revises: b7667adf8487
Create Date: 2025-05-04 17:18:06.340818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beb9c950e5d3'
down_revision = 'b7667adf8487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('count_review', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('count_review')
        batch_op.drop_column('avg_rate')

    # ### end Alembic commands ###
